name: job_portal
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.2.4
  get: ^4.6.6
  google_sign_in: ^6.2.1
  http: ^1.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.7
  rename_app: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

icons_launcher:
  image_path: "assets/icon.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
