// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoP6cFB6FRu0Uw9SZ8P4kAUaRESYjUUaQ',
    appId: '1:189471613106:android:e0817f80d342c52b2aa9ab',
    messagingSenderId: '189471613106',
    projectId: 'job-portal-9ed1b',
    storageBucket: 'job-portal-9ed1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtcxrX1VwZBJCoFpKEgnH0Y5Xuc_cutHY',
    appId: '1:189471613106:ios:17fc6f860ea60d7c2aa9ab',
    messagingSenderId: '189471613106',
    projectId: 'job-portal-9ed1b',
    storageBucket: 'job-portal-9ed1b.appspot.com',
    androidClientId: '189471613106-vlt02q1jco70np13f9mbhmh2m774p136.apps.googleusercontent.com',
    iosClientId: '189471613106-puhhdpu73kmbgrd3pe2qfltbcjtsv6aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobPortal',
  );
}
